### ISSUE TITLE
Simple is not good if path is too long

### ISSUE THREAD

**Issue by sotayamashita** [fisherman/simple#5]
If terminal window width is short, path cannot be displayed. I will fix it to listen terminal window size and if tis size is smaller than path. the path will be abbreviated path like `~/Documents/projects/simple` -> `~/D/p/simple`. I do not know whether I can fix or not. 

ref: 

* http://stackoverflow.com/questions/263890/how-do-i-find-the-width-height-of-a-terminal-window
* http://stackoverflow.com/questions/5243445/bash-command-to-change-size-of-bash-window
* http://unix.stackexchange.com/questions/61584/how-to-solve-the-issue-that-a-terminal-screen-is-messed-up-usually-after-a-res

**Comment by sotayamashita** [comment]
@brj what do you think ?

**Comment by brj** [comment]
You could achieve what you want using `tput`, but what about just using `prompt_pwd`?

**Comment by sotayamashita** [comment]
@brj I do not use `prompt_pwd` in default because I think it is difficult to understand. 

* Get terminal window size `set -l window tput`
* Get full path length. `path | wc -c | sed 's/ //g'`
* Compare between both.

Looks good ?

**Comment by brj** [comment]
>  I think it is difficult to understand.

What part you don't understand?

`prompt_pwd` is just a function that returns the abbreviated path.

To the get the path length use:

```fish
echo "$PWD" | awk '{print(length($0))}'
```

or

```fish
string length "$PWD"
```

**Comment by sotayamashita** [comment]
@brj 

> What part you don't understand?

Because I am not familiar with short path so when I developing and then I try to remove directory, I have to change short path to long one.

**Comment by sotayamashita** [comment]
I close it because if I i add a feature, it will not be simple.
