### ISSUE TITLE
Update prompt when jumping around path history

### ISSUE THREAD

**Issue by halicki** [fisherman/simple#6]
Hi everyone!
I found an annoying issue. Whenever I jump around path history using Alt+Arrow Keys, the prompt is either not updated at all (if jumping up in path) or is distorted (when a jumping inside a git repo - git branch name and status is being written over previous path string).

Here's a snippet:

initial:

```
ahalicki at cubiarek in ~/Praca/ci/Harvest on master [?]
❯ cd bInstall/                                                             09:01
```

If path is expanding is OK
```
ahalicki at cubiarek in ~/Praca/ci/Harvest/bInstall on master [?]               
❯                                                                          09:02
```

But here after Alt+Left Arrow is rubbish:
```
ahalicki at cubiarek in ~/Praca/ci/Harvest on master [?]aster [?]
❯                                                                          09:04
```

**Comment by jbucaran** [comment]
Hi @halicki. Help understand the problem again. First, what is that `[?]`?

**Comment by halicki** [comment]
@jbucaran The `master [?]` is the current git branch name (`master`) and its status (`[?]` means modified/).

**Comment by halicki** [comment]
@jbucaran I think that the example that I presented is misleading. The issue happens even if user is jumping between non git paths. I will update the description.

**Comment by jbucaran** [comment]
Let's ping @sotayamashita, the author of this prompt to see if he has any feedback.

In the meantime, hang on, or try any other of the available themes would you? Run `fisher ls-remote` to see what you can install.

**Comment by halicki** [comment]
Cleaner description:
```
ahalicki at cubiarek in ~/test
❯ ls                                                                       14:51
baaaaar/  fooo/

ahalicki at cubiarek in ~/test
❯ cd fooo/                                                                 14:51

ahalicki at cubiarek in ~/test/fooo
❯ cd ../baaaaar/                                                           14:52

ahalicki at cubiarek in ~/test/baaaaar
❯                                                                          14:52
```
now press Alt+LeftArrow
```
ahalicki at cubiarek in ~/test/foooaar
❯                                                                          14:52

```

**Comment by jbucaran** [comment]
@halicki I understand the issue now, what I am confused about now is this Alt+←/→ binding that I have never heard of.

How does that work and where is the documentation for that?

**Comment by halicki** [comment]
@jbucaran it's on fish documentation page. It's one of the main features of fish ;-)
It's a second entry from: https://fishshell.com/docs/current/index.html#shared-binds
> Alt← and Alt→ move the cursor one word left or right, or moves forward/backward in the directory history if the command line is empty. If the cursor is already at the end of the line, and an autosuggestion is available, Alt→ (or AltF) accepts the first word in the suggestion.

**Comment by jbucaran** [comment]
@halicki I thought you meant moving into directories when you said "jumping", I don't know why I thought that! I didn't know fish had this key binding, useful indeed :)

So, I installed the prompt, but I couldn't repro it, maybe I didn't try hard enough. Let's wait to hear from the author.

**Comment by sotayamashita** [comment]
@jbucaran Thank you for answering the issue. I am catching up it...

**Comment by halicki** [comment]
@sotyayamashita no problem!

**Comment by sotayamashita** [comment]
@halicki I tried same things which you did ([ref](https://github.com/fisherman/simple/issues/6#issuecomment-267598600)) but I cannot get the kind of bug :bug:. 

Here is my environment:
- OSX 
- fisherman version 2.11.0
- fish, version 2.4.0

**Comment by halicki** [comment]
@sotayamashita: I have the same environment, with exception to fisherman (2.10.0 - I think that the latest release, ref: [fisherman/fisherman/releases](https://github.com/fisherman/fisherman/releases)).

I think that maybe I am still not understood properly. The prompt isn't displayed properly although the directory is successfully changed. I'll demonstrate it again, if you allow ;)

```
arek at air in ~
❯ cd foo                                                                              17:54

arek at air in ~/foo
❯                                                                                     17:54
```
Press Alt + LeftArrow: (_does not update the prompt_). 
```
arek at air in ~/foo
❯                                                                                     17:55
```
Press Enter: (_prints prompt with changed directory_)
```
arek at air in ~/
❯                                                                                     17:55
```

So to have clearly displayed path I need to press Enter each time I jump trough path history. This is pretty annoying when searching trough long path history.

This issue was reproduced by me on my private macOS running iTerm and at work on Ubuntu 16.04 running gnome terminal. On both machines I was testing with or without tmux.

**Comment by alexrussell** [comment]
OSX user here, I get a similar non-updating on alt+left (until you get to the 'root' and then try alt+left once more) but it works fine on alt+right.

**Comment by sotayamashita** [comment]
@halicki @alexrussell 

I completely understand what problem is and I am trying to fix this issue but If you have any idea, please tell me :bow:
